steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east4-docker.pkg.dev/ecommerce-microserivces/nestjs-ecommerce-registry/products-ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/ecommerce-microserivces/nestjs-ecommerce-registry/products-ms",
      ]
options:
  logging: CLOUD_LOGGING_ONLY